### ISSUE TITLE
Digitalocean API v2 Officially Leaves Beta

### ISSUE THREAD

**Issue by corndogcomputers** [koalalorenzo/python-digitalocean#105]
As of this morning, api v2 is no longer beta. Does this mean we are ready for python-digitalocean v1.5 to get pushed to PyPi?

[API v2 Officially Leaves Beta](https://www.digitalocean.com/company/blog/apiv2-officially-leaves-beta/)

**Comment by koalalorenzo** [comment]
I am going to push this now! I had a small problem with my current internet connection, but I will push this in few minutes. Meanwhile use the master branch :+1:

**Comment by corndogcomputers** [comment]
:+1:
