### ISSUE TITLE
Requests is not doing its job (decoding gzip encoded stuff)

### ISSUE THREAD

**Issue by convexset** [koalalorenzo/python-digitalocean#107]
The following snippet says it all:

>>> import requests
>>> import zlib
>>> 
>>> headers = {"Content-Type": "application/json",
...            "Authorization": "Bearer "+DIGITALOCEAN_TOKEN}
>>> 
>>> r = requests.get("https://api.digitalocean.com/v2/account/keys", headers=headers)
>>> print (r.text) # Binary gibberish
u'\x1f\ufffd\x08\x00\x00\x00\x00\x00\x00\x03mR\u066e\ufffd@\x14\ufffd\ufffd\ufffd~\ufffd\x19\ufffd\x06\ufffdNn2(^\x14\ufffd\ufffd\x05\ufffd\ufffdd\ufffdt\ufffd\n\ufffd\u0266h\ufffd\ufffda\ufffdy\ufffd\ufffdIUN\ufffd\ufffd\ufffd\x0bT\ufffd\ufffd\ufffd\ufffdu\x15@?_ \ufffd\x00)P\ufffd<\x1c\ufffdS\ufffd\ufffdYY\ufffdQV\x03\x04h\ufffd\ufffd\ufffd DPA#\x01\x11\x19i<\x12\t\ufffd\x1aR%D)\x12\x05D\x05\ufffd\ufffd(<!\ufffd\ufffd!(\ufffd0\ufffd\ufffd_\ufffd^\u07a7|++\ufffd\ufffd\ufffd3\ufffd\ufffd\x13O\ufffd\ufffd\ufffd\ufffd\x7ft~\ufffd7\u0545\ufffd\ufffd^\x07\ufffd\ufffd(\u04f9f\ufffd\ufffd(\ufffd\x06\u0409oYP\ufffd\ufffd\ufffd\ufffd\ufffd\x10\ufffdR\ufffdu#\ufffd.EM.}>\ufffd\ufffd$\ufffd\ufffd\x0e\ufffd\ufffd:\ufffd5\ufffdz!\ufffd\ufffdd\ufffd\x19\ufffd{\ufffd1ek\ufffd\ufffd\x05\ufffd3w\u04d1_\ufffd{\ufffdc\ufffd\x11f>]\ufffd\ufffdym\ufffd\ufffd\ufffd\u0792\ufffd\ufffd\ufffd\ufffd\x15\ufffd\x14\ufffd\ufffd\u06d6O\ufffd\ufffd/rT\ufffd\ufffd\x13\ufffd\ufffdQ7\ufffd\ufffd|\ufffd|\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u051et%\x0e\ufffd\ufffd\x02{\ufffd\ufffd\ufffd\ufffd\ufffd\x06\ufffdk\ufffd\x10\ufffd*\ufffd\ufffd\ufffdf\ufffd\x15\ufffd\ufffd\ufffdY\ufffdT\ufffd:[c\ufffd\ufffd\x0bC\ufffd\u02fd2\ufffd\x13\xe8!\ufffd6\u0725\ufffd\x1232\ufffd\ufffd\u02a0\ufffd\u019e\ufffd1~\u06a9\ufffd5\ufffd\ufffdN\ufffd\ufffdAg~\u05b9\ufffdVI\ufffd\x04\ufffd\u2b0e\u0311\ufffd\ufffd5\ufffd}u\ufffd\\v\ufffdWp\x0f\ufffd?,\x0f\ufffd\ufffd4\x0e\u072ea\ufffd\ufffd\ufffd=\u0359S\ufffdj\ufffd\ufffd;\ufffdx\ufffd\ufffd\ufffd y\u05b2G\ufffd\ufffd\x1f\ufffd\x14G\ufffdw\ufffd\ufffd}?\x19NY\ufffd\ufffd\ufffd\ufffd\ufffd_C\ufffdD\u0675\x7f\ufffd\ufffd{\x08RV\ufffd\x1e\ufffd:\ufffdq\x02\ufffd\ufffd~\ufffd\x01T\ufffd#\ufffd7\x02\x00\x00'
>>> r.content # Binary gibberish
'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03mR\xd9\xae\xa2@\x14\xfc\x95\x9b~\xd5\x19\x96\x06\x81Nn2(^\x14\x95\xc5\x05\xc5\xc9d\xd2t\xb7\n\xb2\xc9\xa6h\xfc\xf7a\xe6y\xce\xc3IUN\xaa\xea\xa1\xce\x0bT\xd5\xe5\xf7\x95u\x15@?_ \xa2\x00)P\x82<\x1c\x82S\x94\x9dYY\x94QV\x03\x04h\x88\xa0\x8c DPA#\x01\x11\x19i<\x12\t\xc2\x1aR%D)\x12\x05D\x05\xa4\xa9(<!\x85\x81!(\x9a0\x89\xc8_\xef^\xde\xa7|++\xfc\xa1\xf73\x86\xf6\x13O\x84\x8e\x88\xd3\x7ft~\xef\xb77\xd5\x85\x8b\x95^\x07\x83\xbd(\xd3\xb9f\xc0\xe7(\xd0\x06\xd0\x89oYP\xe4\xb9\xc2\xf9\xfb\xfc\x10\xedR\xe8u#\xb8.EM.}>\xc6\xce$\x9c\x8d\x0e\xc1\xed:\xad5\xee\xacz!\x9d\xc8d\x99\x19\xb9{\xbc1ek\x8a\xc6\x05\xe3\xb83w\xd3\x91_\xeb{\xb1c\xa4\x11f>]\x96\xf1ym\xca\xde\xf3\xde\x92\xb0\xb1\xa5\xa7\x15\xef\x14\x87\x97\xdb\x96O\x9d\x9d/rT\xa2\xf1\xa2\x13\x85\xbcQ7\xb6\xd9|\xe9\x87|\x99\xa8\xae\xa4\xb1\x95\xd4\x9et%\x0e\xd2\xc3\x02{\xa2\xdb\xf8\xb2\xe9\x06\xe3k\x97\x10\xb9*\x83\x88\x8ef\x92\x15\x84\xba\x91Y\xedT\xf8:[c\xc1\xa5\x0bC\x80\xcb\xbd2\xd8\x13\xc3\xa8!\x966\xdc\xa5\xd8\x1232\xb9\xc5\xca\xa0\xeb\xc6\x9e\x901~\xda\xa9\xee5\xbc\xbcN\xac\xbbAg~\xd6\xb9\xf3\xa2VI\xf2\x9c\x04\x85\xe2\xac\x8e\xcc\x91\xac\xf95\xc8}u\x93\\v\xb6Wp\x0f\x9a?,\x0f\x87\xcb4\x0e\xdc\xaea\x99\xfe\xb5=\xcd\x99S\xb5j\xa9\xdc;\xeex\xff\xfc\xfc y\xd6\xb2G\xc5\xea\x1f\xe7\x14G\xc9w\x92\xa7}?\x19NY\xdf\xcc\xff\x8e\xef_C\x90D\xd9\xb5\x7f\x8a\xd7{\x08RV\xe3\x1e\x81:\xafq\x02\x90\xf0~\xff\x01T\xdb#\x867\x02\x00\x00'
>>> print (zlib.decompress(r.content, 16+zlib.MAX_WBITS)) # Decompress and say hello to my public key.
{"ssh_keys":[{"id":734303,"fingerprint":"db:35:33:37:61:c5:90:2c:a9:84:dd:21:d1:98:bf:7e","public_key":"ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1hJmk++W25dI9D3z6Y9+3OjqnYpoo7/VWoXiUm3Qy63Rr295rV0jaOCbH6XYqkEt9/g8QbdC5cLnDoPZqe7TG2DhaajyGUE6VtAW2yecu1HVdLrjgRG5QzwvcbuN4zJjU7O05vv0mOUV2/d4djKy21ou8SNGuFAXoLl8P49eM4vfA7jYmXKaQ2PuV5GPYBkylc5srYid6H4JYbADnJvE1FgJB1PdKD13LW7+WcDDt3a4S/hpTcGiG/KMDdRuNCcBazNmAQu05RlJwDdHVnyPIpt8clzCYp7OMZeO4JIkYoV8SlhUNQp/xdoxJQabLmjYPyuenAFTfIeOsv8r7wy/Zw== convexset@gmail.com","name":"convexset@gmail.com"}],"links":{},"meta":{"total":1}}

Here's what's in r.headers (note content-encoding):

{'cache-control': 'max-age=0, private, must-revalidate',
 'cf-ray': '1dba5fd98f7a17b6-SIN',
 'connection': 'keep-alive',
 'content-encoding': 'gzip',
 'content-type': 'application/json; charset=utf-8',
 'date': 'Thu, 23 Apr 2015 14:49:20 GMT',
 'ratelimit-limit': '5000',
 'ratelimit-remaining': '4981',
 'ratelimit-reset': '1429801676',
 'server': 'cloudflare-nginx',
 'set-cookie': '__cfduid=d5df7a2d5f73dd12bdd87d2f9cec562c41429800559; expires=Fri, 22-Apr-16 14:49:19 GMT; path=/; domain=.digitalocean.com; HttpOnly',
 'status': '200 OK',
 'transfer-encoding': 'chunked',
 'x-content-type-options': 'nosniff',
 'x-frame-options': 'SAMEORIGIN',
 'x-request-id': 'e8292c02-5fcc-4105-b7e6-4643dca05ac7',
 'x-runtime': '0.027317',
 'x-xss-protection': '1; mode=block'}

**Comment by convexset** [comment]
This is the reply from curl (which seems to automatically decompress):

< HTTP/1.1 200 OK
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< Date: Thu, 23 Apr 2015 14:58:09 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d5c1fb13695ce4338c5c1e5743d0445e51429801088; expires=Fri, 22-Apr-16 14:58:08 GMT; path=/; domain=.digitalocean.com; HttpOnly
< Status: 200 OK
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< RateLimit-Limit: 5000
< RateLimit-Remaining: 4979
< RateLimit-Reset: 1429801676
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: 3b4b9f00-f489-408e-867d-1bf6e4176434
< X-Runtime: 0.029200
< CF-RAY: 1dba6cc2a087081d-SIN
< 
* Connection #0 to host api.digitalocean.com left intact
{"ssh_keys":[{"id":734303,"fingerprint":"db:35:33:37:61:c5:90:2c:a9:84:dd:21:d1:98:bf:7e","public_key":"ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1hJmk++W25dI9D3z6Y9+3OjqnYpoo7/VWoXiUm3Qy63Rr295rV0jaOCbH6XYqkEt9/g8QbdC5cLnDoPZqe7TG2DhaajyGUE6VtAW2yecu1HVdLrjgRG5QzwvcbuN4zJjU7O05vv0mOUV2/d4djKy21ou8SNGuFAXoLl8P49eM4vfA7jYmXKaQ2PuV5GPYBkylc5srYid6H4JYbADnJvE1FgJB1PdKD13LW7+WcDDt3a4S/hpTcGiG/KMDdRuNCcBazNmAQu05RlJwDdHVnyPIpt8clzCYp7OMZeO4JIkYoV8SlhUNQp/xdoxJQabLmjYPyuenAFTfIeOsv8r7wy/Zw== convexset@gmail.com","name":"convexset@gmail.com"}],"links":{},"meta":{"total":1}}

**Comment by koalalorenzo** [comment]
Can you show me the error/problem connected with the line of code of python-digitalocean?

**Comment by convexset** [comment]
I'm using requests (2.6.1) btw...

>>> import digitalocean
>>> manager = digitalocean.Manager(token=DIGITALOCEAN_TOKEN)
>>> my_droplets = manager.get_all_droplets()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/digitalocean/Manager.py", line 82, in get_all_droplets
    data = self.get_data("droplets/")
  File "/usr/local/lib/python2.7/site-packages/digitalocean/Manager.py", line 32, in get_data
    data = super(Manager, self).get_data(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/digitalocean/baseapi.py", line 108, in get_data
    'Read failed from DigitalOcean: %s' % e.message
digitalocean.baseapi.JSONReadError: Read failed from DigitalOcean: Expecting value: line 1 column 1 (char 0)

Same issue with other libraries it seems. Root cause should be requests.

**Comment by koalalorenzo** [comment]
Can you run the tests? Have you tried with other machines or OSs?

**Comment by convexset** [comment]
No. If it works fine on your end it may be a strange local issue with requests.

So I've run the tests. (They all pass.) I've also had a look at them. They are mocking requests, so everything comes back as well-formed JSON.

The case of 'content-encoding': 'gzip' just does not happen.

**Comment by koalalorenzo** [comment]
Try on another machine: it maybe be a problem with your gzip. It seems not to be a issue related to this Python library! Check that ;-)

Inviato da iPhone

**Comment by convexset** [comment]
I've tried it on another machine. The same thing happens on a Mac and Centos Linux.

Anyway, modifying the `get_data` method of the `BaseAPI` object in `baseapi.py` to handle this case quickly fixes the issue at no real cost.

>
            if 'content-encoding' in req.headers and req.headers['content-encoding'] == 'gzip':
                # deal with case when content remains compressed
                data = json.loads(zlib.decompress(req.content, 16+zlib.MAX_WBITS))
            else:
                data = req.json()
>

It's up to you if you'd like to use this.

**Comment by koalalorenzo** [comment]
Which OS are you using? what is the version? This sounds strange to me but I will check. Probably it is better to notify python requests too! https://github.com/kennethreitz/requests

**Comment by convexset** [comment]
CentOS Linux release 7.0.1406 (Core) (Python Python 2.7.5 via yum; requests 2.6.1)
and
OS X Yosemite 10.10.2 (Python 2.7.9 via Brew; requests 2.6.1)

**Comment by koalalorenzo** [comment]
Closed as fixed by python requests team. See #108
