### ISSUE TITLE
Erroneous comments in droplet.destroy()

### ISSUE THREAD

**Issue by artfullyContrived** [koalalorenzo/python-digitalocean#112]
Currently droplet.destroy looks like this

```python
    def destroy(self):
        """
            Destroy the droplet
            Optional Args:
                return_dict - bool : Return a dict when True (default),
                    otherwise return an Action.
            Returns dict or Action
        """
        return self.get_data("droplets/%s" % self.id, type=DELETE)
```

Either the comments should be corrected to reflect the actual situation (no args accepted), or the function should be changed to accept the optional arg `return_dict` and return a `dict` or an `Action`. Currently it returns a `boolean`?

**Comment by koalalorenzo** [comment]
I think that the method you are looking for is wrong written. I may made a mistake when merging some requests and probably one of them was ignoring these cases: the developer should decide if get an Action or a dict of information!

Thanks

**Comment by moyamo** [comment]
The DigitalOcean API doesn't return an action when you delete the droplet. The method is correct. The documentation is wrong. I think I accidentally added that docstring when adding return_dict to the other methods.

**Comment by koalalorenzo** [comment]
Should I close this? it seems not to be a bug.

**Comment by artfullyContrived** [comment]
Once the documentation is corrected it should be closed.
