### ISSUE TITLE
Add ability to wait for droplet creation/destruction

### ISSUE THREAD

**Issue by artfullyContrived** [koalalorenzo/python-digitalocean#113]
It would be desirable if there was a way to wait untill droplet creation and destroying are completed.

A good way would be to return an Action in the said functions.
Thus it would be possible to say

    droplet.create().wait(5)

or

    droplet.destroy.wait(5)

Those are the functions that I have interacted with, there could be more that want the same treatment.

**Comment by koalalorenzo** [comment]
Actually this is possible.
Every Action object has the wait() method.

https://github.com/koalalorenzo/python-digitalocean/blob/master/digitalocean/Action.py

This will allow you to wait until the action is completed. Just let the method (reboot, start, destroy) return an action object, not the dictionary, and use the method wait()

**Comment by moyamo** [comment]
@koalalorenzo `droplet.create()` and `droplet.destroy()` do not return Actions or dictionaries so it is not possible to use the `wait()` method. The DigitalOcean API does not return an Action for the destroy command. However, for the create command, it sends something that looks like an Action ID. This fact is not well documented so I'm not sure if this is a Droplet Action that can be queried at `/droplets/DROPLET_ID/actions/ACTION_ID` or just an Action which needs to be queried at `/actions/ACTION_ID`.

@artfullyContrived You can try to do this so long

     droplet.create()
     action = Action(id=droplet.action_ids[0], token=droplet.token, droplet_id=droplet.id)
     action.wait()

I doubt  that this will work, but you can try it.

**Comment by robreiss** [comment]
@moyamo your example almost worked for me, I needed to add a "load" call to the action before waiting for it. Thanks, your comment helped me out.

    droplet.create()
    action = Action(id=droplet.action_ids[0], token=droplet.token, droplet_id=droplet.id)
    action.load()
    action.wait(5)
    # now the droplet has been created, therefore I can use it to attach a floatingip
    fip = digitalocean.FloatingIP(ip='45.55.xxx.xxx', token=droplet.token)
    fip.assign(droplet_id=droplet.id)
