### ISSUE TITLE
Missing attributes in droplet object after creating new droplet

### ISSUE THREAD

**Issue by PabloCastellano** [koalalorenzo/python-digitalocean#114]
After creating a droplet using the piece of code from the README:

```
import digitalocean
droplet = digitalocean.Droplet(token="secretspecialuniquesnowflake",
                               name='Example',
                               region='nyc2', # New York 2
                               image='ubuntu-14-04-x64', # Ubuntu 14.04 x64
                               size_slug='512mb',  # 512MB
                               backups=True)
droplet.create()
```

the response from the API provides data about the just created instance like the id. The id is setted as attribute of the droplet object, as seen here:

https://github.com/koalalorenzo/python-digitalocean/blob/master/digitalocean/Droplet.py#L495

however other attributes are not setted. I find interesting to be able to access to droplet.ip_address at least. Does it make sense that I submit a patch for this? Other attributes could be set too, like memory or ip_v6_address.

More information about returned data at https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet (see Response Body)

**Comment by koalalorenzo** [comment]
If you have a clear idea about how you want to implement this, feel free to do it! For now the solution is to load the droplet right after it's creation, but probably save 1 call, would be better! :+1: Great idea!

**Comment by PabloCastellano** [comment]
Now I realize I wasn't looking at the correct response body. ip_address is only returned when you retrieve an existing droplet. Sorry about it.

However I'm submitting a PR to add the following attributes: 'vcpus', 'disk', 'created_at', 'locked', 'status', 'features'.  Feel free to merge it or not!
