### ISSUE TITLE
Droplet with unique name

### ISSUE THREAD

**Issue by murugannode** [koalalorenzo/python-digitalocean#129]
It's possible to create droplet with unique name using this API

**Comment by koalalorenzo** [comment]
Well, if this is a question, you can do it by checking the already existing droplets' name in your code:
```python 
    def is_already_there(manager, droplet_name):
        my_droplets = manager.get_all_droplets()
        for droplet in my_droplets:
            if droplet.name == droplet_name
                return True
        return False
```

So you want to use this quick method to check if the droplet name is already used. ;-)
