### ISSUE TITLE
Support for creating multiple droplets with a single API call

### ISSUE THREAD

**Issue by goodcode** [koalalorenzo/python-digitalocean#142]
Recently DigitalOcean added this feature: https://developers.digitalocean.com/documentation/v2/#create-multiple-droplets

Do you have any plans for supporting this in the future?

**Comment by koalalorenzo** [comment]
Not yet, since I am really busy. If you have time and you want to implement it, feel free to open a new pull request.

**Comment by goodcode** [comment]
https://github.com/koalalorenzo/python-digitalocean/pull/143

**Comment by koalalorenzo** [comment]
Closing since we are working there. We can keep talking in #143
