### ISSUE TITLE
Create droplet with SSH keys

### ISSUE THREAD

**Issue by texnic** [koalalorenzo/python-digitalocean#144]
Hello, I am very new here, but I hope I am posting in the right place.
First, thanks a ton for this library, it's awesome! It works like charm, and I was able to progress very quickly, except for one annoying hiccup: I cannot make DigitalOcean accept my keys for the newly created droplet. This is what I'm doing:

    m = digitalocean.Manager(token=token_str)
    keys = m.get_all_sshkeys()
    key_ids = [];
    for key in keys:
        key_ids.append(key.id)
    print(key_ids)  # this returns the correct number of IDs
    
    droplet = digitalocean.Droplet(token=token_str,
                                   name='Example',
                                   region='ams3',
                                   image='ubuntu-14-04-x64',
                                   size_slug='512mb',
                                   backups=False,
                                   ssh_key_ids=key_ids)

    droplet.create()
 

The droplet is created just fine, but I cannot connect to it via Putty! So I was wondering if the code above was correct.

**Comment by koalalorenzo** [comment]
Probably this error is related to #138. It may be a problem of using multiple ssh keys. WIP ;-)

**Comment by texnic** [comment]
Saw that thread, but couldn't understand it :) Also it ended with a 3 week
old commit. So I thought it was closed already.
Also in my case it doesn't seem to work even with a single key.

Isn't it a blocking issue? If I cannot create a droplet with a key, I can't
SSH to the newly created droplet, since the password is sent by email. Am I
correct? Is there maybe a known workadround?

**Comment by koalalorenzo** [comment]
That is correct, you should receive a password via email. The fix for the SSH key should be ready as soon as we have tests ready for the latest changes. (Soon in master, and published).

**Comment by koalalorenzo** [comment]
I have just noticed that:

- You don't need to convert the keys into a list of IDs it is done already by the python-digitalocean to transform python objects into the proper API format.
- The code you shared is using a property called "ssh_key_ids" but in the documentation (and in the DO APIs) it is required to use "ssh_keys". 

This is how you can do it:

```python
manager = digitalocean.Manager(token="secretspecialuniquesnowflake")
keys = manager.get_all_sshkeys()

droplet = digitalocean.Droplet(token="secretspecialuniquesnowflake",
                               name='DropletWithSSHKeys',
                               region='ams3', # Amster
                               image='ubuntu-14-04-x64', # Ubuntu 14.04 x64
                               size_slug='512mb',  # 512MB
                               ssh_keys=keys #Automatic conversion
                               )
droplet.create()
```

I will update the Readme file to include this. It is working for me on my Mac :-) I have tested it manually.
Sorry for this delay but I have been SUPER busy until now.

**Comment by texnic** [comment]
Lorenzo, it works, you are awesome, thanks!
By the way, have I missed something, or the only documentation for your library is indeed the  readme at https://github.com/koalalorenzo/python-digitalocean/blob/master/README.md? Just in order not to bug you next time with something you already described somewhere.

**Comment by koalalorenzo** [comment]
You can see/read the documentation also using help() or reading the source code. Every method and every class has a documentation (I am really stricter about it).

If tomorrow I have some spare time I will try to generate some docs so we will not have this silly problems 👍 I am sorry for not having done it before

**Comment by texnic** [comment]
Thanks for expanding my Python knowledge! I'll try do document my code on for usability with help(). Cheers.

**Comment by koalalorenzo** [comment]
Marked as "invalid" just because it was not an issue related to the code...
I forgot also to say that you can navigate it easily with pydoc ;-)
