### ISSUE TITLE
Can't get DO droplet to use the SSH key in python-digitalocean

### ISSUE THREAD

**Issue by archbungle** [koalalorenzo/python-digitalocean#157]
Hi 

 I'm creating a droplet with:

---
def build_new_droplet(d_name):
 droplet = digitalocean.Droplet(token=my_token,
 name=d_name,
 region='nyc2',
 image='ubuntu-14-04-x64',
 size_slug='512mb',
 ssh_key_ids=[my_sshkey_id],
 backups=True)
 results=droplet.create()
 print "droplet data> ",results
---

... But when I ssh using the key (ssh -i <keyname> root@<droplet IP> ... I get asked for a password.
When I ssh in using the password, I can see that there is nothing in root's authorized_keys file.

thanks for any help!

**Comment by koalalorenzo** [comment]
What is the content of my_sshkey_id ?
Have you trie to follow the instructions as in the examples? (in the readme file)

**Comment by omrivolk** [comment]
Very similar problem, I copy-pasted the example with the keys and created a few droplets, the ssh-keys did not work when I used an ELK logging stack image instead of ubuntu. That was the only thing I changed.

**Comment by koalalorenzo** [comment]
@omrivolk probably you need to talk to DO support for that. It means that they were not able to push the SSH keys inside the instance.

**Comment by omrivolk** [comment]
Well I don't think so, since If I do it using the website I can have that image start with my key

**Comment by koalalorenzo** [comment]
please check #144
