### ISSUE TITLE
Kernel details

### ISSUE THREAD

**Issue by fabaff** [koalalorenzo/python-digitalocean#161]
The details about the kernel can not be retrieved at the moment via Python. This was found while I was working on a integration into [Home Assistant](https://github.com/home-assistant/home-assistant/pull/3322).

```bash
$ python3
>>> import digitalocean
>>> api_key ='xxxxxxx'
>>> droplet = digitalocean.Droplet(token=api_key, id='2534242')
>>> print(droplet.name)
fedora-512mb-nyc3-01
>>> print(droplet.kernel)
None 
```
`curl` doesn't work either. To make sure that the problem is not at my end, I created a question at [DO](https://www.digitalocean.com/community/questions/unable-to-retrieve-kernel-details-via-api)) too. Just to avoid that my limited knowledge about Digital Ocean is the source.

**Comment by andrewsomething** [comment]
I answered over on the [DO site](https://www.digitalocean.com/community/questions/unable-to-retrieve-kernel-details-via-api), but wanted to follow up here too. This is not a bug in python-digitalocean. Newer DigitalOcean Droplets use their own bootloaders and “internally managed” kernels. For these Droplets, the kernel attribute will be `null`.

**Comment by fabaff** [comment]
Thanks for your response.
