### ISSUE TITLE
Volume actions unimplemented

### ISSUE THREAD

**Issue by zultron** [koalalorenzo/python-digitalocean#171]
I'm using this wonderful API wrapper to automatically provision coreos machines on DO.  Thanks to the devs for this great work.

It looks like `Volume` actions aren't implemented, unless I'm doing something wrong.  The README shows an example similar to this:

```
droplet = digitalocean.Droplet(...)
droplet.create()
actions = droplet.get_actions()
for action in actions:
    action.load()
    print action.status
```

The equivalent for a `Volume` might be:

```
# This works:
volume = digitalocean.Volume(...)
volume.create()  # (This actually returns a dict containing action data)
# This would be awesome:
actions = volume.get_actions()
for action in actions:
    action.load()
    print action.status
```

I haven't looked carefully.  Could this be implemented using the same `digitalocean.Action` class that handles droplet actions?

**Comment by koalalorenzo** [comment]
The main goal (that is hard to reach) is to keep the library structure similar to the API provided by DO.
You can find for sure more information by reading the source code, or just by using `help(digitalocean.Volume)`. Let me know if you need more help!
