### ISSUE TITLE
'module' object has no attribute 'Manager'

### ISSUE THREAD

**Issue by matthewwf** [koalalorenzo/python-digitalocean#173]
Hi,

I have just installed this via pip and I get - 'module' object has no attribute 'Manager' when I run the following...

import digitalocean
manager = digitalocean.Manager(token="MySecretTokenxxxxxxxxxxxxxxxxxxxxxxxxx")
my_droplets = manager.get_all_droplets()
print(my_droplets)

Any help is much appreciated.

Thanks

Matthew

**Comment by koalalorenzo** [comment]
Are you using the right module? Have you installed `python-digitalocean` correctly?
Is this issue still affecting you? (I think it is not a project issue)

**Comment by thomasave** [comment]
Do you by any chance have a file called digitalocean.py in your current directory?

**Comment by matthewwf** [comment]
I don’t seem to be able to find that file in my virtualenv.


Kind Regards,

Matthew

**Comment by matthewwf** [comment]
Sorry, I have found this location but not the file you mentioned –

/sites/[Project Name]/env/lib/python2.7/site-packages/digitalocean


Kind Regards,

Matthew

**Comment by koalalorenzo** [comment]
Can you check if the python path.
I may suggest to try it in a VM/Virtualenv/Container

**Comment by thomasave** [comment]
That should be fine, but I was wondering if you named one of your own files the same as one from python-digitalocean. Could you provide the complete error message? For example, when I have a file named "digitalocean.py" in my current directory:
`Traceback (most recent call last):
  File "digitalocean.py", line 1, in <module>
    import digitalocean
  File "/home/billie/digitalocean.py", line 4, in <module>
    manager = digitalocean.Manager(token=token)
AttributeError: module 'digitalocean' has no attribute 'Manager'
`
I can immediately see which digitalocean-file it is trying to import.

**Comment by matthewwf** [comment]
Hi,

I have just removed and installed it again and this time it appear to be working, although as I am using python2.7 it is giving me ssl warnings.

Thanks for your help


Kind Regards,

Matthew

**Comment by koalalorenzo** [comment]
Check the requirements to use SSL with python requests: https://github.com/koalalorenzo/python-digitalocean/issues/109
