### ISSUE TITLE
Domains get records result problem

### ISSUE THREAD

**Issue by ozgurkuru** [koalalorenzo/python-digitalocean#175]
Hello,

Get recrods method returns only id of record. When I don't know id of record, I cant search with record name

**Comment by koalalorenzo** [comment]
This has been an issue related to the DigitalOcean API structure, that would require a little of _computation_ to fix it. This library won't do that as it is meat to provide an interface.

But, probably they have updated the API.

**Comment by koalalorenzo** [comment]
Please reopen in case, PR are welcome to change behaviour or update the code according to the API.
