### ISSUE TITLE
Wrong Action id in multiple_create

### ISSUE THREAD

**Issue by ozgurkuru** [koalalorenzo/python-digitalocean#176]
Hello,

Return action_id is wrong, when use multiple_create function.

For Example;

multi=droplet.create_multiple(
        token="xxxxxx",
        names= ['name'],
        size= "1gb",
        image= "21543467",
        region= "fra1",
)

for id in multi:
    action_id =  id.action_ids
    droplet_id = id.id
    print action_id

this code print [181960013] as action id but When I list all of actions; I see 181960015 action id for created droplet

**Comment by koalalorenzo** [comment]
Do this still occurs to you? Have you checked in the code to find out some more information or do you still need help?

**Comment by koalalorenzo** [comment]
I have tried to simulate this without much success. Please re open this if needed!
