### ISSUE TITLE
Documentation Published Anywhere

### ISSUE THREAD

**Issue by sumdog** [koalalorenzo/python-digitalocean#186]
Is the documentation available anywhere (and if so, can you add a link to the Readme?)

I have no problem reading the source code, but I notice you have a build process for docs and wondered if you considered putting them somewhere like readthedocs.org? It might make it easier for others. 

Thanks for this API btw. I've found it incredibly useful.

**Comment by andrewsomething** [comment]
There is: http://digitalocean.readthedocs.io/en/latest/ But it is currently still pointed at @WoLpH's fork. python-digitalocean.readthedocs.io might be a be domain in order to be clear what's there.

**Comment by koalalorenzo** [comment]
@sumdog Thanks for the message, I probably update the readme. ATM you can just check the source code or use the `help()` function directly from python.

**Comment by WoLpH** [comment]
Oops... now that pull request #181 has been merged that url should change back. I've updated the url at readthedocs :)

@koalalorenzo do you have an account on readthedocs? I can answer the ownership to you if you do :)

**Comment by koalalorenzo** [comment]
Yes I do :) Go ahead

**Comment by WoLpH** [comment]
I forgot to reply here, but I've given you access straight after your reply :)

**Comment by mkinney** [comment]
I think this issue is resolved. Close?
