### ISSUE TITLE
SSH Keys bound to an instance not returned.

### ISSUE THREAD

**Issue by ZeeshanSultan** [koalalorenzo/python-digitalocean#193]
The droplet object has ssh_keys attribute but returns an empty list even if a key is attached to that instance and is running properly.

![digitalocean](https://cloud.githubusercontent.com/assets/8667667/24752637/43d6b2d8-1ae8-11e7-8c04-58b810befa44.jpg)

**Comment by koalalorenzo** [comment]
The ssh_keys are used only when creating a droplet, as the value is stored inside `authorized_keys` file ;-)
