### ISSUE TITLE
Adding tags to droplets broken

### ISSUE THREAD

**Issue by WoLpH** [koalalorenzo/python-digitalocean#196]
The code which I'm using (this worked with earlier versions):
```
tag = digitalocean.Tag(token=TOKEN, name=NAME)
tag.create()
droplets = list('bunch of Droplet() objects here')
tag.add_droplets(droplets)
```

The stacktrace:
```
Traceback (most recent call last):
  File "manage_droplets.py", line 286, in <module>
    main()
  File "manage_droplets.py", line 267, in main
    tag.add_droplets(droplets)
  File "digitalocean/Tag.py", line 125, in add_droplets
    return self.__add_resources(resources)
  File "digitalocean/Tag.py", line 76, in __add_resources
    return self.__get_resources(resources, method='POST')
  File "digitalocean/Tag.py", line 64, in __get_resources
    type=method,
  File "digitalocean/baseapi.py", line 161, in get_data
    raise NotFoundError()
digitalocean.baseapi.NotFoundError
```

**Comment by koalalorenzo** [comment]
Can you check if this is an API change,
PR are welcome.

**Comment by WoLpH** [comment]
I've done a bit of extra testing and it appears it's mainly the tag creation that's broken. When using existing tags it appears to work. Perhaps that's why it was never noticed before?

**Comment by WoLpH** [comment]
No... it's even weirder. Perhaps it's a bug in the DO API but it's not consistently reproducible any way I try right now.

Perhaps DO had some temporary issues or so but this code consistently didn't work for several days and now it's working without a hitch... I'll report back if I encounter it again
