### ISSUE TITLE
Ansible package support?

### ISSUE THREAD

**Issue by chavenor** [koalalorenzo/python-digitalocean#210]
This seems to be more current than the older packages tied into Ansible.  Is there any desire to implement this directly with the Ansible modules? 

https://github.com/ansible/ansible/pull/25105

**Comment by koalalorenzo** [comment]
PR are more than welcome.
Since after few years, DO decided to remove my credit (gained as prize for creating this project), I am maintaining the project by accepting and checking PRs, and few polishing. Nothing more than that.

If you want to integrate with Ansible, feel free to open a PR!
