### ISSUE TITLE
Trying to create tags dosn't work.

### ISSUE THREAD

**Issue by chavenor** [koalalorenzo/python-digitalocean#211]
Keeps on saying Unable to authenticate you.  Yet I'm able to create droplets with the same key.

**Comment by chavenor** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Casey\Envs\test-website\lib\site-packages\digitalocean\Tag.py", line 40, in create
    output = self.get_data("tags/", type="POST", params=params)
  File "C:\Users\Casey\Envs\testwebsite\lib\site-packages\digitalocean\baseapi.py", line 172, in get_data
    raise DataReadError(msg)
digitalocean.baseapi.DataReadError: Unable to authenticate you.
```

**Comment by koalalorenzo** [comment]
Sounds weird, I am not able to test it, but, have you tried to re-create the API token?

**Comment by chavenor** [comment]
Same token works with you API to create droplets.  I'll have to come back to this no time.   I hard coded my code to work.

**Comment by koalalorenzo** [comment]
If you fixed it, please share the code! 👍

**Comment by chavenor** [comment]
Wrote a cusotme module from scratch outside of the lib.  Will come back to it when I have time.

**Comment by koalalorenzo** [comment]
Can you give more details about this error? Is this a bug or something? What was the code you were running?

We have tests so maybe we can improve them by using the problem you had!

**Comment by chavenor** [comment]
I do not have the code for that example I will let you know if it comes up again I think we can close this out.
