### ISSUE TITLE
too many outbound SSH connections at once from running API

### ISSUE THREAD

**Issue by yinleon** [koalalorenzo/python-digitalocean#222]
Hi, 

I was wondering if anyone else has had security issues from too many outbound SSH connections at once. I am running the API to create droplets and attach volumes and I have gotten warnings from my systems administrators. 

I am a total noob with this kind of stuff, and it likely isn't an issue with the API.

**Comment by koalalorenzo** [comment]
Seems weird, but this library is not related to that. Double check the security of your linux box, and try to use [mosh](https://mosh.org) 😉
