### ISSUE TITLE
Droplet info

### ISSUE THREAD

**Issue by umardraz** [koalalorenzo/python-digitalocean#226]
Hello how I can get all the information of a droplet 

like

for droplet in my_droplets:
    droplet.name
   droplet.ram ?

etc

**Comment by tallus** [comment]
vars(droplet) will get you a dict of the droplet attributes (name: value)
```python
for var_name, value in vars(droplet).items():
    print "{}: {}".format(var_name, value)
```

**Comment by umardraz** [comment]
Thanks :)
