### ISSUE TITLE
firewall example doesnt work

### ISSUE THREAD

**Issue by rstevens011** [koalalorenzo/python-digitalocean#231]
I can seem to be able to use the firewall example.  Specifically it fails to import the Firewall object:  
```
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from digitalocean import Firewall
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Firewall
>>> 
```

The docs also dont mention Firewall related objects either.

**Comment by koalalorenzo** [comment]
Why don't you install the version of the git repository manually?
Is it making a difference? 

I should make a new release soon

**Comment by wacuuu** [comment]
By the fact this sits here for 2 years almost, I suggest to close this @koalalorenzo

**Comment by rvanlaar** [comment]
This seems to work now. I had no problems importing it when I tried using firewalls. 
I'm on version: 1.14.0
