### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by duesenfranz** [koalalorenzo/python-digitalocean#250]
After stumbling upon the tag API bug fixed [back in february](https://github.com/koalalorenzo/python-digitalocean/commit/faccab32bc4985d95714556e2593a58dc1ebd919), I noticed that the last update on pip was [back in december](https://pypi.org/project/python-digitalocean/#history). Would it be possible to update the pip package to reflect the recent fixes/improvements?

**Comment by koalalorenzo** [comment]
I was waiting for the PR to be updated honestly

**Comment by WoLpH** [comment]
Can you release an intermediate version perhaps? It'se been 6 months since [this](https://github.com/koalalorenzo/python-digitalocean/pull/239) pull request and I still have to install from git manually ;)

**Comment by teran-mckinney** [comment]
I could also use this. What is it that you were looking to be updated?

**Comment by koalalorenzo** [comment]
I am on it, I would like to use gitlab to enable this automagically on master branch :)

**Comment by WoLpH** [comment]
with Travis that's literally just a few lines of code to enable: https://docs.travis-ci.com/user/deployment/pypi/

perhaps a nice option for you :)

**Comment by koalalorenzo** [comment]
I found gitlab much more powerful and useful (and integrated with everything I need). 
Have you tried that? :) 

I will use it.

**Comment by WoLpH** [comment]
I've used Gitlab quite extensively for a few of my customers but I've never tried pypi releases that way. So far I've always found Github more convenient for open source projects with the simple reason that more people use it.

I'll take a look though, Travis is a tad too quirky for my taste. I've had a fair share of problems with them

**Comment by scott-hand** [comment]
Bump. I just ran into the Python 3 unicode error for tagging droplets. Any ETA?

**Comment by alchemyconsulting** [comment]
Bump, just hit tag error.  Please release a new version - whatever changes might be made with the management of the module shouldn't get in the way of fixing major bugs.

**Comment by koalalorenzo** [comment]
Just released as requested. If you find problems please open a PR as I am not actively developing it, but I am maintaining it for contributors

**Comment by alchemyconsulting** [comment]
@koalalorenzo thanks :)  and thanks for a great project, just came across it today and it's working really well.
