### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by jepler** [koalalorenzo/python-digitalocean#252]
I had a minor disaster related to using python-digitalocean to manipulate domain records since python-digitalocean does not seem to implement pagination.

According to https://developers.digitalocean.com/documentation/v2/#links and https://developers.digitalocean.com/documentation/changelog/api-v2/tweak-per-page/ things are by default paginated 20 items per page.  Based on experimentation, this is the case with DNS records.

As a result, when it was working with a name that was not on the first "page" within its domain, my script kept failing to find an existing DNS record to modify, and created a new one instead. (yes, my script should have done other things like keep track of the numeric identifier of its record, but there you go)

When I found this out, the cloud control panel showed that I had over 12,000 records in my domain(!).  I'm cleaning things out with `doctl`, which is able to issue requests like `GET /v2/domains/…/records?page=2&per_page=200` to retrieve all the data.

**Comment by koalalorenzo** [comment]
_Ouch!_ I am so sorry for this! 
if you have a quick fix for this, I am willing to accept a PR 👍

**Comment by jepler** [comment]
Everything's under control, but it was a bit of a surprise and at first I didn't understand the cause.

Unfortunately, I don't have a fix for python-digitalocean, I am just resorting to using doctl at this time instead.

**Comment by jepler** [comment]
argh, it looks like I have an outdated version of python-digitalocean installed, so let me test with a current version.  Apparently I do not know how to use `pip` properly to get the latest version (omitted the -U flag).  :blush:

**Comment by jepler** [comment]
I apologize for wasting your time.
