### ISSUE TITLE
Can't tag a newly created Droplet

### ISSUE THREAD

**Issue by Newah1** [koalalorenzo/python-digitalocean#253]
In the official DO documentation I see that they accept tags on the creation of a droplet  ( see https://screenshots.firefox.com/vZlVo89xtKaKCFGC/developers.digitalocean.com ) but I have been unable to find any such functionality here.

Can anyone point me in the right direction, or confirm that this doesn't exist?

**Comment by koalalorenzo** [comment]
You can pass the `tags` parameter when creating a droplet.

https://github.com/koalalorenzo/python-digitalocean/blob/master/digitalocean/Droplet.py#L95

**Comment by Newah1** [comment]
Perfect, thank you so much, sorry to take your time. 👍
