### ISSUE TITLE
Support for updating domain records

### ISSUE THREAD

**Issue by bdawg24601** [koalalorenzo/python-digitalocean#254]
Please add support for updating domain records.

**Comment by wacuuu** [comment]
https://github.com/koalalorenzo/python-digitalocean/pull/270 Is this the PR by chance?

**Comment by qencode-dev** [comment]
Hi team, just noticed you have enabled supported for updating and deleting domain records in the github repo, but PyPi still has the old version. Meanwhile we just manually patched installed version but you might want to update it on PyPi :)
