### ISSUE TITLE
Help - Docs

### ISSUE THREAD

**Issue by ayoubensalem** [koalalorenzo/python-digitalocean#255]
This is some really good library :+1:  , yet it lacks docs. 
To help yourself, refer to digital ocean api to get things done quickly : https://developers.digitalocean.com/documentation/v2

**Comment by koalalorenzo** [comment]
It has a lot of docs but those are inline :) Sorry I am closing this issue as the Docs of the API should work fine by design, but I am not maintaining that much anymore.
