### ISSUE TITLE
Make endpoint url configurable

### ISSUE THREAD

**Issue by varac** [koalalorenzo/python-digitalocean#267]
The [digitalocean API endpoint URL is hardcoded in baseapi.py](https://github.com/koalalorenzo/python-digitalocean/blob/9ff1137a12a1df1fae52b7ba64318fba01b21da9/digitalocean/baseapi.py#L46).
Please make it configurable so we can use this module against other providers that implemented the DO API.

[A quick search for `api.digitalocean.com`](https://github.com/koalalorenzo/python-digitalocean/search?q=api.digitalocean.com&unscoped_q=api.digitalocean.com) revealed some other places where the URL is hardcoded.

**Comment by wacuuu** [comment]
Is there a case in which endopint is changable even? Or this is a nice to have option in case api changes at some point in the future?

**Comment by varac** [comment]
@wacuuu I'm using a hosting provider who implemented the DO api (greenhost.net), and I guess there will be others that do the same.

**Comment by mkinney** [comment]
I think this issue is resolved. Close?

**Comment by varac** [comment]
Nice, thanks !
