### ISSUE TITLE
Support for Projects (feature request)

### ISSUE THREAD

**Issue by iDemonix** [koalalorenzo/python-digitalocean#269]
Hi,

I use my DO account for personal and business, and I keep things organised with Projects. Projects are supported fully in the DO API, but not in the library.

Before I fork and get coding, I wondered if this was a feature that you'd consider a PR for, or something you've already got in the pipeline?

Thanks for the great work on the module.

**Comment by koalalorenzo** [comment]
Thanks for the message,
No I am not planning to support it but you are more than welcome to creat a new PR.

**Comment by iDemonix** [comment]
Thanks for the quick reply. I do need it so I think I'll fork and add the functionality. I'm not a developer by nature, so I'm not to clued up on tests, but if I get everything working I can look in to writing some and submit a PR for merge.

Cheers
