### ISSUE TITLE
Get deleted Droplet results in digitalocean.NotFoundError

### ISSUE THREAD

**Issue by raceybe** [koalalorenzo/python-digitalocean#271]
When get_droplet() is run on an id for a deleted droplet, a `digitalocean.NotFoundError` results. Instead of throwing the error, can it be modified to return a null droplet, or similar?

**Comment by koalalorenzo** [comment]
This is following the API implementation, so if the API is throwing an error, it should do the same. 

What is the case, issue, pain you are having with the current implementation?

**Comment by raceybe** [comment]
That's a fair response. Originally I was expecting a None result, but I now see that doesn't make sense. I'll close the issue.
