### ISSUE TITLE
Full or Partial Support for Projects

### ISSUE THREAD

**Issue by kbknapp** [koalalorenzo/python-digitalocean#290]
First off, thank you for this library! It's excellent!

I see in #269 you're not interested in supporting Projects, so is there a possibility of supporting some kind of "raw API call" which would allow us to build off what you've already got?

Really the only thing I need is to create a simple project, and place droplets built using the API into said project. I don't need anything else, which is why I think some kind of raw API builder could work.

Thanks again!

**Comment by kbknapp** [comment]
I just saw #289 as well which I'm excited for.

**Comment by koalalorenzo** [comment]
Closing as #300 got merged and published
