### ISSUE TITLE
Deleting snapshots

### ISSUE THREAD

**Issue by peterkodermac** [koalalorenzo/python-digitalocean#291]
I'm able to successfully create a snapshot and then get a list of snapshots with get_all_snapshots().

How do I delete a snapshot that has been taken?

**Comment by jotyGill** [comment]
If you want to find your snap by name.
Iterate through them (manager.get_all_snapshots()), till you find your snapshot name.
Once you find the match, get it's id or if you already have the id.

get that snap `digitalocean.Snapshot.get_object(do_token, snap.id)` snap object, call `your_snapshot_obj.destroy()`

Checkout function find_snapshot from my project [dobackup](https://github.com/jotyGill/digitalocean-backup/blob/master/dobackup/dobackup.py)

You can also just use dobackup to do all of that.

**Comment by GOPIPACHA** [comment]
> I'm able to successfully create a snapshot and then get a list of snapshots with get_all_snapshots().
> 
> How do I delete a snapshot that has been taken?

Can you Help me out How did you created snapshot?

**Comment by peterkodermac** [comment]
> > I'm able to successfully create a snapshot and then get a list of snapshots with get_all_snapshots().
> > How do I delete a snapshot that has been taken?
> 
> Can you Help me out How did you created snapshot?

sure can! This is my whole code:
https://gist.github.com/peterkodermac/d9f5bbeeb8b70cfae8a3abb3d4e67799
