### ISSUE TITLE
Publish a new version; API error

### ISSUE THREAD

**Issue by jotyGill** [koalalorenzo/python-digitalocean#295]
Hi,
Thank you for this amazing project.
Could you please publish a new release. Specifically the changes implemented in Actions.py in #272 
The old implementation used to work until recently, now when trying to get an action it throws 404 error.
Basically anything using pypi version and trying to directly get Action objects would error out.

`
2019-11-20 10:56:21,473 [DEBUG]  https://api.digitalocean.com:443 "GET /v2/droplets/None/actions/806510502?per_page=200 HTTP/1.1" 404 None`
`2019-11-20 10:56:21,476 [WARNI]  CATCHING digitalocean.baseapi.Error, TRYING AGAIN
`

**Comment by vovinacci** [comment]
@jotyGill Thanks much for the fix!
@koalalorenzo Could you please-please-please push this to PyPi? :) That would be very much appreciated.

**Comment by koalalorenzo** [comment]
I will look into something to automate that, I think I have started doing this with GitLab CI/CD but I stopped. Will restart doing it soon, I will release a new version after merging some PR

**Comment by vovinacci** [comment]
@koalalorenzo Thank you very much for update and cannot wait for new release to happen!

**Comment by koalalorenzo** [comment]
A new version has been published, please let me know if the problems are still persisting.
