### ISSUE TITLE
Getting "NotFoundError" when using take_snapshot with power_off=True

### ISSUE THREAD

**Issue by vithickvi** [koalalorenzo/python-digitalocean#298]
When using power_off=True geting NotFoundError.

**Comment by vithickvi** [comment]
Yes, it's been there like more than a year. I simply shut down and took a snapshot

**Comment by koalalorenzo** [comment]
I do believe you need to shut down before taking a snapshot. (right? 🤔 ). Probably that is why the API is providing that error. Closing for now.
