### ISSUE TITLE
Documentation says "complete", but it is "completed"

### ISSUE THREAD

**Issue by petervandenabeele** [koalalorenzo/python-digitalocean#304]
I tried this code:

```
for action in actions:
    action.load()
    status = action.status
    print(status)
    while status != "complete":
        sleep(5)
        action.load()
        status = action.status
        print(status)
```

But that runs in an infinite loop, because the actual status for completed is "completed"

The documentation says:

"Once it shows complete, droplet is up and running"

I suggest to change that to:

"Once it shows `completed`, droplet is up and running"

And ... is there an existing "blocking" call that will only return when the creation was either successfully completed or failed or timed-out ?

Thanks :-)

**Comment by koalalorenzo** [comment]
Thank you for noticing this, I will update it
