### ISSUE TITLE
Track bandwidth used

### ISSUE THREAD

**Issue by teran-mckinney** [koalalorenzo/python-digitalocean#310]
I looked through Digital Ocean's documentation and I don't see any way to track bandwidth used per Droplet. Do you know if I'm missing something?

Would be a rather nice feature to have.

**Comment by koalalorenzo** [comment]
Thank you Teran!
I don't think this is a feature that the library can provide if it is not provided by the API itself... I am not sure. I think I have to close it for now. If this is or will be some data exposed as an API, please feel free to reopen the issue or contribute directly with a PR 😃
