### ISSUE TITLE
can't able to creat LoadBalancer

### ISSUE THREAD

**Issue by GOPIPACHA** [koalalorenzo/python-digitalocean#313]
Hi All,

I am trying to creaye the loadbalancer from quitre long time but i am getting Traceback error.Below is my sample python code for creating LB,

import digitalocean
droplet = digitalocean.LoadBalancer(token="API- Token",
                                    name= 'check',
                                    region=  'BLR1'
                                    forwarding_rules=  ['entry_protocol:http',
                                               'entry_port:80',
                                               'target_protocol:http',
                                               'target_port:80']))
droplet.create()

when i try to execute the above code i am getting error like below
'''
Traceback (most recent call last):
  File "/home/mypathshala-1/PycharmProjects/digital_ocen/LB.py", line 9, in <module>
    lb.create()
  File "/home/mypathshala-1/PycharmProjects/digital_ocen/venv/lib/python3.7/site-packages/digitalocean/LoadBalancer.py", line 210, in create
    rules_dict = [rule.__dict__ for rule in self.forwarding_rules]
  File "/home/mypathshala-1/PycharmProjects/digital_ocen/venv/lib/python3.7/site-packages/digitalocean/LoadBalancer.py", line 210, in <listcomp>
    rules_dict = [rule.__dict__ for rule in self.forwarding_rules]
AttributeError: 'str' object has no attribute '__dict__'

Can anyone help me out how can create a LoadBalancer and how can i add a droplet to it?

Thanks in advance.

**Comment by GOPIPACHA** [comment]
Can annyone help  me out on this issue please

**Comment by GOPIPACHA** [comment]
Will i get any responce ?

**Comment by koalalorenzo** [comment]
Hi, sorry for the late (super late) reply.
Check how to create new rules [from this guide](https://github.com/koalalorenzo/python-digitalocean#creating-a-firewall). I do believe that it could have been the issue! 

Closing as it has been a long time since the last update, but if anything: please feel free to re-open the issue!
