### ISSUE TITLE
License Change?

### ISSUE THREAD

**Issue by dmaust** [koalalorenzo/python-digitalocean#33]
I suppose it's too late to suggest a license change? I would think this library would be much better suited for a Apache, BSD, or LGPL license over the GPL.

I noticed there are several contributers, so a change in license might be tricky, but thought I'd throw it as an idea in case others feel the same.

**Comment by wallrj** [comment]
It's a shame. This seems to be the best and most active DigitalOceanV2 wrapper but we can't use for running cloud acceptance tests in https://github.com/ClusterHQ/flocker which is Apache licensed.
 * https://github.com/ClusterHQ/flocker/pull/1043#issuecomment-70076810
