### ISSUE TITLE
Should be able to specify ssh key by fingerprint

### ISSUE THREAD

**Issue by Janzert** [koalalorenzo/python-digitalocean#76]
When creating a droplet you should be able to give a key fingerprint to Droplet.create(). The current code tries to interpret any string as an actual public key.

Adding an additional check to see if it's a fingerprint, instead of a full public key, after finding a string in Droplet.__get_ssh_keys_id and then directly adding the fingerprint to the id list allows it to work.

**Comment by moyamo** [comment]
See https://github.com/koalalorenzo/python-digitalocean/pull/77

This might be what you are looking for. However it assumes your ssh_key is 16 pairs of hexadecimal digits separated by a colon.
