### ISSUE TITLE
long and unicode not defined in python 3

### ISSUE THREAD

**Issue by moyamo** [koalalorenzo/python-digitalocean#80]
Since python 3 is supported, it should be noted that long and unicode are not defined in python 3 (u'string literal' still works). This is a problem for __get_ssh_key_id_or_fingerprint in Droplet. A possible solution would be

           try:
                inttype = [int, long]
                strtype = [str, unicode]
            except NameError:
                inttype = [int]
                strtype = [str]

By the way, many of the unit tests fail on python 3.

**Comment by koalalorenzo** [comment]
I noticed this now, I tested using py.test with the python 2. I will start working on it tomorrow, but feel free to open some pull requests if you need!

**Comment by koalalorenzo** [comment]
Is this bug still there with the updated version @moyamo ? It is working for me

**Comment by moyamo** [comment]
No, I think you fixed it.

**Comment by moyamo** [comment]
By updated, you mean the master branch right?

**Comment by koalalorenzo** [comment]
Yes

**Comment by moyamo** [comment]
Yes, commit a3ca206 fixed this bug
