### ISSUE TITLE
Module "re" should be imported in Droplet.py

### ISSUE THREAD

**Issue by moyamo** [koalalorenzo/python-digitalocean#82]
This one is my fault. I used regular expressions in Droplet.__get_ssh_keys_id_or_fingerprint, but forgot to import re. Just add

    import re

to the top of Droplet.py

Note [https://github.com/koalalorenzo/python-digitalocean/pull/81] also fixes this issue. But you can add this as a separate commit.

I'm really sorry, this was such a stupid mistake.

**Comment by koalalorenzo** [comment]
I really thing that this bug is fixed
