### ISSUE TITLE
Private networking not enabled when requested

### ISSUE THREAD

**Issue by etxeba** [koalalorenzo/python-digitalocean#87]
Tested this in two regions that offer private networking. The code below reproduces the problem. SSH_KEY_ID is a valid ssh key fingerprint. Droplets are successfully created, but private networking is not enabled.
```    
    new_droplet = Droplet(
            name='newserver',
            size_slug='1gb',
            image='ubuntu-14-04-x64',
            region='nyc2',
            private_networking=True,
            ssh_keys=[SSH_KEY_ID],
            backups_enabled=False,
            token=TOKEN)
    new_droplet.create()
```

**Comment by koalalorenzo** [comment]
Probably this is connected with the #86, Can you check that?

**Comment by tomscytale** [comment]
actually #85 contains the fix for private networking - #86 fixes handling of the `ssh_keys` parameter which was broken by #85

**Comment by koalalorenzo** [comment]
Great! I am going to test and for the end of the day I will publish a new release with these fixes, I hope this will be solved. @etxeba can you check if the master branch works for you fixing the problem?

Thanks.

**Comment by etxeba** [comment]
@koalalorenzo Current master works great. Thanks!

**Comment by koalalorenzo** [comment]
Perfect!
