### ISSUE TITLE
tests break when run the old-fashioned way

### ISSUE THREAD

**Issue by tomscytale** [koalalorenzo/python-digitalocean#90]
python2.7 in a virtualenv
```
python-digitalocean$ python digitalocean/tests/test_droplet.py 
Traceback (most recent call last):
  File "digitalocean/tests/test_droplet.py", line 7, in <module>
    from .BaseTest import BaseTest
ValueError: Attempted relative import in non-package
```

Also it would be nice if there was a single test file to run instead of 3 separate ones.

**Comment by koalalorenzo** [comment]
What about if you run py.test ?

**Comment by tomscytale** [comment]
Ahhhhhh - you're using pytest - I just realised it's in requirements.txt.

48a5bf96ec6273ca752ee3fa7309574617ad9354
