### ISSUE TITLE
record destroy not working correctly, but thyere is a work around.

### ISSUE THREAD

**Issue by lgfausak** [koalalorenzo/python-digitalocean#92]
Having an issue with record.destroy, here is my code:

```
        manager = digitalocean.Manager(token=args.token)
        my_domains = manager.get_all_domains()
        for domain in my_domains:
            dns = domain.get_records()
            for dr in dns:
                logging.debug("dr domain is %s", dr.domain)
                if args.id:
                    logging.debug("looking for %d in %d:%s", args.id, dr.id, dr.name)
                    if dr.id == args.id:
                        logging.info("deleting the dns record %d, %s", dr.id, dr.name)
                        dr.domain = domain.name
                        dr.destroy()
```

I looked at the source, the destroy() method needs the self.domain and self.id to prime the digitalocean api.  The id is there, but, self.domain is "".  In the init method is it set to blank, I didn't look any further because I don't know what is going on there.  I could *force* it to work using the line before the destroy call 'dr.domain = domain.name'.

**Comment by koalalorenzo** [comment]
I will have a look at this later today, but probably if you have time for a pull request, I will be more than happy to accept it! :-)

**Comment by moyamo** [comment]
There's a simple fix where you pass the domain name in when `get_records` is called.
