### ISSUE TITLE
private networking issue

### ISSUE THREAD

**Issue by derrend** [koalalorenzo/python-digitalocean#94]
Hello,

Here is a code snippet I am trying to use to create a droplet:

    droplet = digitalocean.Droplet(token=secret,
        name=domain,
        region='sgp1', # Singapore 1
        ssh_keys=[default_key],
        image='centos-6-5-x64', # Centos 6.5 x64
        size_slug='512mb',  # 512MB
        backups=False,
        private_networking=True)

My droplets are created successfully except private networking is always disabled.
I receive no error during droplet creation.

Thanks

**Comment by koalalorenzo** [comment]
What if you use the Master branch of this repository? I think this problem is fixed. See #92 #93 and let me know! :+1:

**Comment by koalalorenzo** [comment]
Is it working if you use the Master branch of the repository?
I will check, probably they changed again the API.

**Comment by derrend** [comment]
I am using version: 1.0.8 according to pip, perhaps I need to upgrade :)
